import matplotlib.pyplot as plt
import pandas
import numpy as np

plt.rcParams["font.family"] = 'Times New Roman'
plt.rcParams["font.style"] = 'normal'
plt.rcParams["font.variant"] = 'normal'
plt.rcParams["font.weight"] = 'normal'
plt.rcParams["font.stretch"] = 'normal'
plt.rcParams["font.size"] = '11'

PI = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/PI+FF.csv")
PI_PSIM = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/PI_PSIM.csv")
PR_PSIM = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/PR_PSIM.csv")
PR = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/PR+FF.csv")
MR = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/MR+FF.csv")
MR_PSIM = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/MR_PSIM.csv")
Rep = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/Rep+FF.csv")
Rep_PSIM = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/Repetitivo_PSIM.csv")
Prop = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/P+FF.csv")
Prop_PSIM = pandas.read_csv("D:/Users/FELIPE/Documents/Mestrado/dissertacao/capitulos/Capitulo4/grid_con/Prop_PSIM.csv")

# ''' Início do Controlador PI + FF'''
# fig = plt.figure()
# curr = fig.add_subplot(211)
# plt.grid(True)
# plt.ylabel("Current (A)")
# volt = fig.add_subplot(212)
# volt.plot(PI["Time"]+0.001208, PI["Rede"], '-', c='darkgreen', lineWidth=1, label='Vgrid', alpha=0.5)
# volt.plot(PI["Time"]+0.001208, PI["Vbus11"], '-', c='blue', lineWidth=2, label='Vbus')
# plt.grid(True)
# plt.ylabel("Voltage (V)")
# plt.xlabel("Time (s)")
# curr.plot(PI["Time"]+0.001208, PI["IL2"], '-', c='red', lineWidth=1, label='Ig')
# curr.grid(True, which='minor', axis='both')
# volt.legend(loc='upper right', shadow=True, fontsize='9')
# curr.legend(loc='upper right', shadow=True, fontsize='9')
# # volt.set(title='Micro inverter connection to the grid')
# volt.set(xlim=[0, 0.3], ylim=[-350, 450])
# curr.set(xlim=[0, 0.3], ylim=[-2, 2])
# volt.grid(True, which='minor', axis='both')
# plt.savefig('PI+FF.png', dpi=1000)
#
# fig = plt.figure()
# curr = fig.add_subplot(111)
# plt.grid(True)
# curr.plot(PI["Time"]+0.001208, PI["Rede"]/300, '-', c='black', lineWidth=2, label='Vgrid/300')
# plt.grid(True)
# plt.xlabel("Time (s)")
# curr.plot(PI_PSIM["Time"], PI_PSIM["Ir"], '-', c='darkgreen', lineWidth=3, label='PSIM', alpha=0.5)
# curr.plot(PI["Time"]+0.001208, PI["IL2"], '-', c='red', lineWidth=1, label='HIL')
# curr.grid(True, which='minor', axis='both')
# curr.legend(loc='upper right', shadow=True, fontsize='12')
# curr.set(xlim=[0.3, 0.33333], ylim=[-2, 2])
# plt.savefig('PI+FFzoom.png', dpi=1000)
# ''' Fim do Controlador PI + FF '''
#
# ''' Início do Controlador PR + FF'''
# fig = plt.figure()
# curr = fig.add_subplot(211)
# plt.grid(True)
# plt.ylabel("Current (A)")
# volt = fig.add_subplot(212)
# volt.plot(PR["Time"]-0.04838, PR["Rede"], '-', c='darkgreen', lineWidth=1, label='Vgrid', alpha=0.5)
# volt.plot(PR["Time"]-0.04838, PR["Vbus11"], '-', c='blue', lineWidth=2, label='Vbus')
# plt.grid(True)
# plt.ylabel("Voltage (V)")
# plt.xlabel("Time (s)")
# curr.plot(PR["Time"]-0.04838, PR["IL2"]-0.1, '-', c='red', lineWidth=1, label='Ig')
# curr.grid(True, which='minor', axis='both')
# volt.legend(loc='upper right', shadow=True, fontsize='9')
# curr.legend(loc='upper right', shadow=True, fontsize='9')
# # volt.set(title='Micro inverter connection to the grid')
# volt.set(xlim=[0, 0.3], ylim=[-350, 450])
# curr.set(xlim=[0, 0.3], ylim=[-2, 2])
# volt.grid(True, which='minor', axis='both')
# plt.savefig('PR+FF.png', dpi=1000)
#
# fig = plt.figure()
# curr = fig.add_subplot(111)
# plt.grid(True)
# curr.plot(PR["Time"]+0.00095, PR["Rede"]/300, '-', c='black', lineWidth=2, label='Vgrid/300')
# plt.grid(True)
# plt.xlabel("Time (s)")
# curr.plot(PR_PSIM["Time"], PR_PSIM["Ir"], '-', c='darkgreen', lineWidth=3, label='PSIM', alpha=0.5)
# curr.plot(PR["Time"]+0.00095, PR["IL2"]-0.1, '-', c='red', lineWidth=1, label='HIL')
# curr.grid(True, which='minor', axis='both')
# curr.legend(loc='upper right', shadow=True, fontsize='12')
# curr.set(xlim=[0.3, 0.33333], ylim=[-2, 2])
# plt.savefig('PR+FFzoom.png', dpi=1000)
# ''' Fim do Controlador PR + FF '''
#
# ''' Início do Controlador MR + FF'''
# fig = plt.figure()
# curr = fig.add_subplot(211)
# plt.grid(True)
# plt.ylabel("Current (A)")
# volt = fig.add_subplot(212)
# volt.plot(MR["Time"]-0.005644, MR["Rede"], '-', c='darkgreen', lineWidth=1, label='Vgrid', alpha=0.5)
# volt.plot(MR["Time"]-0.005644, MR["Vbus11"], '-', c='blue', lineWidth=2, label='Vbus')
# plt.grid(True)
# plt.ylabel("Voltage (V)")
# plt.xlabel("Time (s)")
# curr.plot(MR["Time"]-0.005644, MR["IL2"]-0.05, '-', c='red', lineWidth=1, label='Ig')
# curr.grid(True, which='minor', axis='both')
# volt.legend(loc='upper right', shadow=True, fontsize='9')
# curr.legend(loc='upper right', shadow=True, fontsize='9')
# # volt.set(title='Micro inverter connection to the grid')
# volt.set(xlim=[0, 0.3], ylim=[-350, 450])
# curr.set(xlim=[0, 0.3], ylim=[-2, 2])
# volt.grid(True, which='minor', axis='both')
# plt.savefig('MR+FF.png', dpi=1000)
#
# fig = plt.figure()
# curr = fig.add_subplot(111)
# plt.grid(True)
# curr.plot(MR["Time"]-0.172333, MR["Rede"]/300, '-', c='black', lineWidth=2, label='Vgrid/300')
# plt.grid(True)
# plt.xlabel("Time (s)")
# curr.plot(MR_PSIM["Time"]-0.3, MR_PSIM["Ir"], '-', c='darkgreen', lineWidth=3, label='PSIM', alpha=0.5)
# curr.plot(MR["Time"]-0.172333, MR["IL2"]-0.05, '-', c='red', lineWidth=1, label='HIL')
# curr.grid(True, which='minor', axis='both')
# curr.legend(loc='upper right', shadow=True, fontsize='12')
# curr.set(xlim=[0, 0.033333], ylim=[-2, 2])
# plt.savefig('MR+FFzoom.png', dpi=1000)
# ''' Fim do Controlador MR + FF '''
#
# ''' Início do Controlador Rep + FF'''
# fig = plt.figure()
# curr = fig.add_subplot(211)
# plt.grid(True)
# plt.ylabel("Current (A)")
# volt = fig.add_subplot(212)
# volt.plot(Rep["Time"]-0.00365, Rep["Rede"], '-', c='darkgreen', lineWidth=1, label='Vgrid', alpha=0.5)
# volt.plot(Rep["Time"]-0.00365, Rep["Vbus11"], '-', c='blue', lineWidth=2, label='Vbus')
# plt.grid(True)
# plt.ylabel("Voltage (V)")
# plt.xlabel("Time (s)")
# curr.plot(Rep["Time"]-0.00365, Rep["IL2"], '-', c='red', lineWidth=1, label='Ig')
# curr.grid(True, which='minor', axis='both')
# volt.legend(loc='upper right', shadow=True, fontsize='9')
# curr.legend(loc='upper right', shadow=True, fontsize='9')
# # volt.set(title='Micro inverter connection to the grid')
# volt.set(xlim=[0, 0.3], ylim=[-350, 450])
# curr.set(xlim=[0, 0.3], ylim=[-2, 2])
# volt.grid(True, which='minor', axis='both')
# plt.savefig('Rep+FF.png', dpi=1000)
#
# fig = plt.figure()
# curr = fig.add_subplot(111)
# plt.grid(True)
# curr.plot(Rep["Time"]-0.237, Rep["Rede"]/300, '-', c='black', lineWidth=2, label='Vgrid/300')
# plt.grid(True)
# plt.xlabel("Time (s)")
# curr.plot(Rep_PSIM["Time"]-0.45, Rep_PSIM["Ir"], '-', c='darkgreen', lineWidth=3, label='PSIM', alpha=0.5)
# curr.plot(Rep["Time"]-0.237, Rep["IL2"]+0.05, '-', c='red', lineWidth=1, label='HIL')
# curr.grid(True, which='minor', axis='both')
# curr.legend(loc='upper right', shadow=True, fontsize='12')
# curr.set(xlim=[0, 0.033333], ylim=[-2, 2])
# plt.savefig('Rep+FFzoom.png', dpi=1000)
# ''' Fim do Controlador Rep + FF '''
# # plt.show()

''' Início do Controlador Prop'''
fig = plt.figure()
curr = fig.add_subplot(211)
plt.grid(True)
plt.ylabel("Current (A)")
volt = fig.add_subplot(212)
volt.plot(Prop["Time"], Prop["Rede"], '-', c='darkgreen', lineWidth=1, label='Vgrid', alpha=0.5)
volt.plot(Prop["Time"], Prop["Vbus11"], '-', c='blue', lineWidth=2, label='Vbus')
plt.grid(True)
plt.ylabel("Voltage (V)")
plt.xlabel("Time (s)")
curr.plot(Prop["Time"], Prop["IL2"]-0.1, '-', c='red', lineWidth=1, label='Ig')
curr.grid(True, which='minor', axis='both')
volt.legend(loc='upper right', shadow=True, fontsize='9')
curr.legend(loc='upper right', shadow=True, fontsize='9')
# volt.set(title='Micro inverter connection to the grid')
volt.set(xlim=[0, 0.3], ylim=[-350, 450])
curr.set(xlim=[0, 0.3], ylim=[-2, 2])
volt.grid(True, which='minor', axis='both')
plt.savefig('Prop+FF.png', dpi=1000)

fig = plt.figure()
curr = fig.add_subplot(111)
plt.grid(True)
curr.plot(Prop["Time"], Prop["Rede"]/300, '-', c='black', lineWidth=2, label='Vgrid/300')
plt.grid(True)
plt.xlabel("Time (s)")
curr.plot(Rep_PSIM["Time"]-0.45, Rep_PSIM["Ir"], '-', c='darkgreen', lineWidth=3, label='PSIM', alpha=0.5)
curr.plot(Prop["Time"], Prop["IL2"]-0.05, '-', c='red', lineWidth=1, label='HIL')
curr.grid(True, which='minor', axis='both')
curr.legend(loc='upper right', shadow=True, fontsize='12')
curr.set(xlim=[0, 0.033333], ylim=[-2, 2])
plt.savefig('Prop+FFzoom.png', dpi=1000)
''' Fim do Controlador Prop + FF '''
plt.show()